=== rhishi/SDF3/sadf/xsd/sdf3-sadf.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="uri:sadf" xmlns="uri:sadf" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="sdf3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sadf" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" default="sadf"/>
      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sadf">
    <xs:complexType>
      <xs:choice minOccurs="2" maxOccurs="2">
        <xs:element ref="structure" minOccurs="1" maxOccurs="1" />
        <xs:element ref="properties" minOccurs="1" maxOccurs="1" />
      </xs:choice>
      <xs:attribute name="name" type="xs:string" default="SADF" />
    </xs:complexType>
  </xs:element>
  <xs:element name="structure">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="kernel" minOccurs="0" maxOccurs="unbounded" />
          <xs:element ref="detector" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:element ref="channel" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="kernel">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="detector">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="ChannelType">
    <xs:restriction base="xs:string">
      <xs:pattern value="data|control" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="channel">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="source" type="xs:string" use="required" />
      <xs:attribute name="destination" type="xs:string" use="required" />
      <xs:attribute name="type" type="ChannelType" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="properties">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kernel_properties" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="detector_properties" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="channel_properties" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="kernel_properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="scenario" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="control" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="consume" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="produce" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="profile" minOccurs="0" maxOccurs="unbounded" />
              </xs:choice>
              <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
          </xs:element>
      </xs:sequence>
      <xs:attribute name="kernel" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="detector_properties">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="scenario" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="control" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="subscenario" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="consume" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="produce" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="profile" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element ref="markov_chain" minOccurs="1" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attribute name="detector" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="control">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="consume">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="tokens" type="xs:positiveInteger" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="produce">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="tokens" type="xs:positiveInteger" use="required" />
      <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="profile">
    <xs:complexType>
      <xs:attribute name="execution_time" type="xs:decimal" default="0" />
      <xs:attribute name="weight" type="xs:decimal" default="1" />
    </xs:complexType>
  </xs:element>
  <xs:element name="markov_chain">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="state" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="scenario" type="xs:string" />
      <xs:attribute name="initial_state" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="state">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="transition" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="subscenario" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="transition">
    <xs:complexType>
      <xs:attribute name="destination" type="xs:string" use="required" />
      <xs:attribute name="weight" type="xs:decimal" default="1" />
    </xs:complexType>
  </xs:element>
  <xs:element name="channel_properties">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="buffer_size" type="xs:positiveInteger" />
      <!-- default buffer_size is -1 (unbounded) -->
      <xs:attribute name="number_of_initial_tokens" type="xs:positiveInteger" />
      <!-- attribute number_of_initial_tokens is for data channels only -->
      <!-- default number_of_initial_tokens is 0 -->
      <xs:attribute name="initial_tokens" type="xs:string"/>
      <!-- attribute initial_tokens is for control channels only -->
      <!-- no initial control tokens are assumed by default -->
      <!-- the string should consist of a comma-separated list of items in the following patterns 'Scenario' or 'Number * Scenario', where 'Number' is a positive integer and 'Scenario' is a scenario name. -->
      <xs:attribute name="token_size" type="xs:positiveInteger" />
      <!-- default token_size is 1 -->
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rhishi/SDF3/sadf/testbench/mpeg4_sp_worst_case_sdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="mpeg4_sp_worst_case_sdf">

<structure>
  <kernel name="VLD"/>
  <kernel name="IDCT"/>
  <kernel name="MC"/>
  <kernel name="RC"/>
  <kernel name="FD"/>

  <channel name="VLD2IDCT" source="VLD" destination="IDCT" type="data"/>
  <channel name="IDCT2RC" source="IDCT" destination="RC" type="data"/>
  <channel name="VLD2MC" source="VLD" destination="MC" type="data"/>
  <channel name="MC2RC" source="MC" destination="RC" type="data"/>
  <channel name="RC2MC" source="RC" destination="MC" type="data"/>
  <channel name="RC2FD" source="RC" destination="FD" type="data"/>
  
  <channel name="FD2VLD" source="FD" destination="VLD" type="data"/>
  <channel name="FD2IDCT" source="FD" destination="IDCT" type="data"/>
  <channel name="FD2MC" source="FD" destination="MC" type="data"/>
  <channel name="FD2RC" source="FD" destination="RC" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="VLD">
   <scenario name="P99">
      <consume channel="FD2VLD" tokens="1"/>
      <produce channel="VLD2IDCT" tokens="1"/>
      <produce channel="VLD2MC" tokens="1"/>
      <profile execution_time="40"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="IDCT">
    <scenario name="P99">
      <consume channel="FD2IDCT" tokens="1"/>
      <consume channel="VLD2IDCT" tokens="1"/>
      <produce channel="IDCT2RC" tokens="1"/>
      <profile execution_time="17"/>
    </scenario>           
  </kernel_properties>

  <kernel_properties kernel="MC">
    <scenario name="P99">
      <consume channel="FD2MC" tokens="1"/>
      <consume channel="VLD2MC" tokens="99"/>
      <consume channel="RC2MC" tokens="1"/>
      <produce channel="MC2RC" tokens="1"/>
      <profile execution_time="390"/>
    </scenario>                  
  </kernel_properties>

  <kernel_properties kernel="RC">
    <scenario name="P99">
      <consume channel="FD2RC" tokens="1"/>
      <consume channel="IDCT2RC" tokens="99"/>
      <consume channel="MC2RC" tokens="1"/>
      <produce channel="RC2MC" tokens="1"/>
      <produce channel="RC2FD" tokens="1"/>
      <profile execution_time="350"/>
    </scenario>             
  </kernel_properties>

  <kernel_properties kernel="FD">
    <scenario name="P99">
      <consume channel="RC2FD" tokens="1"/>
      <produce channel="FD2VLD" tokens="99"/>
      <produce channel="FD2IDCT" tokens="99"/>
      <produce channel="FD2MC" tokens="1"/>
      <produce channel="FD2RC" tokens="1"/>
    </scenario>
  </kernel_properties>

  <channel_properties channel="RC2MC" number_of_initial_tokens="1"/>
  <channel_properties channel="RC2FD" number_of_initial_tokens="3"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="example1">

<structure>
  <kernel name="A"/>
  <kernel name="B"/>
  <kernel name="C"/>
  <kernel name="D"/>

  <detector name="E"/>

  <channel name="A2B" source="A" destination="B" type="data"/>
  <channel name="B2A" source="B" destination="A" type="data"/>
  <channel name="B2C" source="B" destination="C" type="data"/>
  <channel name="C2D" source="C" destination="D" type="data"/>
  <channel name="D2B" source="D" destination="B" type="data"/>
  <channel name="A2E" source="A" destination="E" type="data"/>
  
  <channel name="E2B" source="E" destination="B" type="control"/>
  <channel name="E2C" source="E" destination="C" type="control"/>
  <channel name="E2D" source="E" destination="D" type="control"/>
</structure>

<properties>
  <kernel_properties kernel="A">
    <scenario name="default">
      <consume channel="B2A" tokens="2"/>
      <produce channel="A2B" tokens="2"/>
      <produce channel="A2E" tokens="1"/>
      <profile execution_time="2"/>
      <profile execution_time="2.1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="B">
    <scenario name="S1">
      <consume channel="D2B" tokens="2"/>
      <consume channel="A2B" tokens="2"/>
      <produce channel="B2C" tokens="3"/>
      <produce channel="B2A" tokens="2"/>
      <profile execution_time="3" weight="1"/>
      <profile execution_time="2.8" weight="4"/>
    </scenario>
    <scenario name="S2">
      <consume channel="D2B" tokens="2"/>
      <consume channel="A2B" tokens="1"/>
      <produce channel="B2C" tokens="2"/>
      <produce channel="B2A" tokens="1"/>
      <profile execution_time="4"/>        
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="C">
    <scenario name="S1">
      <consume channel="B2C" tokens="1"/>
      <produce channel="C2D" tokens="2"/>
      <profile execution_time="1"/>
      <profile execution_time="1.2"/>
    </scenario>
    <scenario name="S2">
      <consume channel="B2C" tokens="1"/>
      <produce channel="C2D" tokens="1"/>
      <profile execution_time="3"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="D">
    <scenario name="S1">
      <consume channel="C2D" tokens="3"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="4"/>
    </scenario>
    <scenario name="S2">
      <consume channel="C2D" tokens="1"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="2.5"/>
    </scenario>
  </kernel_properties>

  <detector_properties detector="E">
    <subscenario name="S1">
      <consume channel="A2E" tokens="1"/>
      <produce channel="E2B" tokens="1"/>
      <produce channel="E2C" tokens="3"/>
      <produce channel="E2D" tokens="2"/>
    </subscenario>
    <subscenario name="S2">
      <consume channel="A2E" tokens="1"/>
      <produce channel="E2B" tokens="2"/>
      <produce channel="E2C" tokens="4"/>
      <produce channel="E2D" tokens="4"/>
    </subscenario>
    <markov_chain initial_state="S1">    
      <state name="S1" subscenario="S1">
        <transition destination="S2"/>
        <transition destination="S3" weight="2"/>
      </state>
      <state name="S2" subscenario="S2">
        <transition destination="S3"/>
      </state>    
      <state name="S3" subscenario="S2">
        <transition destination="S1"/>
      </state>    
    </markov_chain>
  </detector_properties>

  <channel_properties channel="B2A" number_of_initial_tokens="2"/>
  <channel_properties channel="D2B" number_of_initial_tokens="3"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="example2">

  <structure>
  <kernel name="A"/>
  <kernel name="B"/>
  <detector name="D"/>
  <channel name="A2B" source="A" destination="B" type="data"/>
  <channel name="B2A" source="B" destination="A" type="data"/>
  <channel name="B2D" source="B" destination="D" type="data"/>
  <channel name="D2A" source="D" destination="A" type="control"/>
  <channel name="D2B" source="D" destination="B" type="control"/>
</structure>

<properties>
  <kernel_properties kernel="A">
    <scenario name="S">
      <produce channel="A2B" tokens="2"/>
      <consume channel="B2A" tokens="1"/>
      <profile execution_time="57" weight="2"/>
      <profile execution_time="19" weight="8"/>
      <profile execution_time="51" weight="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="B">
    <scenario name="S">
      <consume channel="A2B" tokens="2"/>
      <produce channel="B2A" tokens="1"/>
      <produce channel="B2D" tokens="1"/>
      <profile execution_time="17" weight="12"/>
      <profile execution_time="5" weight="5"/>
      <profile execution_time="47" weight="2"/>
    </scenario>
    <scenario name="T">
      <produce channel="B2D" tokens="1"/>
      <profile execution_time="13" weight="1"/>
      <profile execution_time="31" weight="13"/>
      <profile execution_time="63" weight="1"/>
    </scenario>
  </kernel_properties>

  <detector_properties detector="D">
    <subscenario name="S">
      <consume channel="B2D" tokens="1"/>
      <produce channel="D2A" tokens="1"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="29" weight="9"/>
      <profile execution_time="3" weight="4"/>
      <profile execution_time="13" weight="1"/>
    </subscenario>
    <subscenario name="T">
      <consume channel="B2D" tokens="1"/>
      <produce channel="D2A" tokens="1"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="7" weight="3"/>
      <profile execution_time="19" weight="1"/>
    </subscenario>
    <markov_chain initial_state="S">
      <state name="S" subscenario="S">
        <transition destination="S" weight="2"/>
        <transition destination="T"/>
      </state>
      <state name="T" subscenario="T">
        <transition destination="S"/>
      </state>
    </markov_chain>
  </detector_properties>
  
  <channel_properties channel="B2D" number_of_initial_tokens="1"/>
  <channel_properties channel="A2B" number_of_initial_tokens="2"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/extended_sdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="extended_sdf">

  <structure>
  <kernel name="Input"/>
  <kernel name="Process"/>
  <kernel name="Output"/>
  <channel name="I2P" source="Input" destination="Process" type="data"/>
  <channel name="P2O" source="Process" destination="Output" type="data"/>
  <channel name="O2I" source="Output" destination="Input" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="Input">
    <scenario name="default">
      <consume channel="O2I" tokens="50"/>
      <produce channel="I2P" tokens="2"/>
      <profile execution_time="17" weight="5"/>
      <profile execution_time="13" weight="6"/>
      <profile execution_time="23" weight="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="Process">
    <scenario name="default">
      <consume channel="I2P" tokens="1"/>
      <produce channel="P2O" tokens="25"/>
      <profile execution_time="7" weight="3"/>
      <profile execution_time="11" weight="7"/>
      <profile execution_time="13" weight="2"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="Output">
    <scenario name="default">
      <consume channel="P2O" tokens="1"/>
      <produce channel="O2I" tokens="1"/>
      <profile execution_time="5"/>
    </scenario>
  </kernel_properties>
  
  <channel_properties channel="O2I" number_of_initial_tokens="100"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/problem18.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="problem18">

<structure>
  <kernel name="A"/>
  <kernel name="B"/>
  <kernel name="C"/>
  <kernel name="D"/>
  <kernel name="E"/>
  <kernel name="F"/>
  <kernel name="G"/>
  <channel name="A2F" source="A" destination="F" type="data"/>
  <channel name="A2C" source="A" destination="C" type="data"/>
  <channel name="B2C" source="B" destination="C" type="data"/>
  <channel name="E2C" source="E" destination="C" type="data"/>
  <channel name="C2D" source="C" destination="D" type="data"/>
  <channel name="D2E" source="D" destination="E" type="data"/>
  <channel name="D2F" source="D" destination="F" type="data"/>
  <channel name="D2G" source="D" destination="G" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="A">
    <scenario name="default">
      <produce channel="A2F" tokens="1"/>
      <produce channel="A2C" tokens="1"/>
      <profile execution_time="2.5" weight="2"/>
      <profile execution_time="1.5" weight="8"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="B">
    <scenario name="default">
      <produce channel="B2C" tokens="2"/>
      <profile execution_time="2"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="C">
    <scenario name="default">
      <consume channel="A2C" tokens="2"/>
      <consume channel="E2C" tokens="1"/>
      <consume channel="B2C" tokens="3"/>
      <produce channel="C2D" tokens="2"/>
      <profile execution_time="1" weight="5"/>
      <profile execution_time="1.2" weight="3"/>
      <profile execution_time="1.5" weight="2"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="D">
    <scenario name="default">
      <consume channel="C2D" tokens="1"/>
      <produce channel="D2E" tokens="1"/>
      <produce channel="D2F" tokens="2"/>
      <produce channel="D2G" tokens="1"/>
      <profile execution_time="2" weight="9"/>
      <profile execution_time="3"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="E">
    <scenario name="default">
      <consume channel="D2E" tokens="2"/>
      <produce channel="E2C" tokens="1"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="F">
    <scenario name="default">
      <consume channel="A2F" tokens="2"/>
      <consume channel="D2F" tokens="4"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="G">
    <scenario name="default">
      <consume channel="D2G" tokens="3"/>
      <profile execution_time="1" weight="2"/>
      <profile execution_time="1.5" weight="8"/>
    </scenario>
  </kernel_properties>
  
  <channel_properties channel="A2F" buffer_size="10"/>
  <channel_properties channel="A2C" buffer_size="10"/>
  <channel_properties channel="B2C" buffer_size="10"/>
  <channel_properties channel="D2G" buffer_size="10"/>
  <channel_properties channel="E2C" number_of_initial_tokens="1"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/problem19.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="problem19">

<structure>
  <detector name="A"/>
  <kernel name="B"/>
  <kernel name="C"/>
  <kernel name="D"/>
  <channel name="A2B" source="A" destination="B" type="data"/>
  <channel name="B2C" source="B" destination="C" type="data"/>
  <channel name="C2D" source="C" destination="D" type="data"/>
  <channel name="D2B" source="D" destination="B" type="data"/>
  <channel name="AB" source="A" destination="B" type="control"/>
  <channel name="AC" source="A" destination="C" type="control"/>
  <channel name="AD" source="A" destination="D" type="control"/>
</structure>

<properties>
  <detector_properties detector="A">
    <subscenario name="s1">
      <produce channel="A2B" tokens="2"/>
      <produce channel="AB" tokens="1"/>
      <produce channel="AC" tokens="3"/>
      <produce channel="AD" tokens="2"/>
      <profile execution_time="2"/>
    </subscenario>
    <subscenario name="s2">
      <produce channel="A2B" tokens="2"/>
      <produce channel="AB" tokens="2"/>
      <produce channel="AC" tokens="3"/>
      <produce channel="AD" tokens="4"/>
      <profile execution_time="2"/>
    </subscenario>
    <subscenario name="s3">
      <produce channel="A2B" tokens="2"/>
      <produce channel="AB" tokens="2"/>
      <produce channel="AC" tokens="4"/>
      <produce channel="AD" tokens="4"/>
      <profile execution_time="2"/>
    </subscenario>
        <markov_chain initial_state="s1">
      <state name="s1" subscenario="s1">
        <transition destination="s2"/>
        <transition destination="s3" weight="4"/>
      </state>
      <state name="s2" subscenario="s2">
        <transition destination="s3"/>
      </state>
      <state name="s3" subscenario="s3">
        <transition destination="s1" weight="2"/>
        <transition destination="s2" weight="5"/>
        <transition destination="s3" weight="3"/>
      </state>
    </markov_chain>
  </detector_properties>

  <kernel_properties kernel="B">
    <scenario name="s1">
      <consume channel="A2B" tokens="2"/>
      <consume channel="D2B" tokens="2"/>
      <produce channel="B2C" tokens="3"/>
      <profile execution_time="3" weight="2"/>
      <profile execution_time="2.8" weight="2"/>
    </scenario>
    <scenario name="s2">
      <consume channel="A2B" tokens="1"/>
      <consume channel="D2B" tokens="2"/>
      <produce channel="B2C" tokens="3"/>
      <profile execution_time="4"/>
    </scenario>
    <scenario name="s3">
      <consume channel="A2B" tokens="1"/>
      <consume channel="D2B" tokens="2"/>
      <produce channel="B2C" tokens="2"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="C">
    <scenario name="s1">
      <consume channel="B2C" tokens="1"/>
      <produce channel="C2D" tokens="2"/>
      <profile execution_time="1"/>
      <profile execution_time="1.2"/>
    </scenario>
    <scenario name="s2">
      <consume channel="B2C" tokens="2"/>
      <produce channel="C2D" tokens="4"/>
      <profile execution_time="3"/>
    </scenario>
    <scenario name="s3">
      <consume channel="B2C" tokens="1"/>
      <produce channel="C2D" tokens="1"/>
      <profile execution_time="5"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="D">
    <scenario name="s1">
      <consume channel="C2D" tokens="3"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="4"/>
    </scenario>
    <scenario name="s2">
      <consume channel="C2D" tokens="3"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="1"/>
    </scenario>
    <scenario name="s3">
      <consume channel="C2D" tokens="1"/>
      <produce channel="D2B" tokens="1"/>
      <profile execution_time="2.5"/>
    </scenario>
  </kernel_properties>
  
  <channel_properties channel="A2B" buffer_size="10"/>
  <channel_properties channel="D2B" number_of_initial_tokens="3"/>

</properties>

</sadf>
</sdf3>
