=== rhishi/SDF3/sadf/xsd/sdf3-sadf.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="uri:sadf" xmlns="uri:sadf" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="sdf3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sadf" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" default="sadf"/>
      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sadf">
    <xs:complexType>
      <xs:choice minOccurs="2" maxOccurs="2">
        <xs:element ref="structure" minOccurs="1" maxOccurs="1" />
        <xs:element ref="properties" minOccurs="1" maxOccurs="1" />
      </xs:choice>
      <xs:attribute name="name" type="xs:string" default="SADF" />
    </xs:complexType>
  </xs:element>
  <xs:element name="structure">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="kernel" minOccurs="0" maxOccurs="unbounded" />
          <xs:element ref="detector" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:element ref="channel" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="kernel">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="detector">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="ChannelType">
    <xs:restriction base="xs:string">
      <xs:pattern value="data|control" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="channel">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="source" type="xs:string" use="required" />
      <xs:attribute name="destination" type="xs:string" use="required" />
      <xs:attribute name="type" type="ChannelType" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="properties">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kernel_properties" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="detector_properties" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="channel_properties" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="kernel_properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="scenario" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="control" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="consume" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="produce" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="profile" minOccurs="0" maxOccurs="unbounded" />
              </xs:choice>
              <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
          </xs:element>
      </xs:sequence>
      <xs:attribute name="kernel" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="detector_properties">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="scenario" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="control" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="subscenario" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="consume" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="produce" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="profile" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element ref="markov_chain" minOccurs="1" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attribute name="detector" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="control">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="consume">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="tokens" type="xs:positiveInteger" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="produce">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="tokens" type="xs:positiveInteger" use="required" />
      <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="profile">
    <xs:complexType>
      <xs:attribute name="execution_time" type="xs:decimal" default="0" />
      <xs:attribute name="weight" type="xs:decimal" default="1" />
    </xs:complexType>
  </xs:element>
  <xs:element name="markov_chain">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="state" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="scenario" type="xs:string" />
      <xs:attribute name="initial_state" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="state">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="transition" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="subscenario" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="transition">
    <xs:complexType>
      <xs:attribute name="destination" type="xs:string" use="required" />
      <xs:attribute name="weight" type="xs:decimal" default="1" />
    </xs:complexType>
  </xs:element>
  <xs:element name="channel_properties">
    <xs:complexType>
      <xs:attribute name="channel" type="xs:string" use="required" />
      <xs:attribute name="buffer_size" type="xs:positiveInteger" />
      <!-- default buffer_size is -1 (unbounded) -->
      <xs:attribute name="number_of_initial_tokens" type="xs:positiveInteger" />
      <!-- attribute number_of_initial_tokens is for data channels only -->
      <!-- default number_of_initial_tokens is 0 -->
      <xs:attribute name="initial_tokens" type="xs:string"/>
      <!-- attribute initial_tokens is for control channels only -->
      <!-- no initial control tokens are assumed by default -->
      <!-- the string should consist of a comma-separated list of items in the following patterns 'Scenario' or 'Number * Scenario', where 'Number' is a positive integer and 'Scenario' is a scenario name. -->
      <xs:attribute name="token_size" type="xs:positiveInteger" />
      <!-- default token_size is 1 -->
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rhishi/SDF3/sadf/testbench/mp3_worst_case_sdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="mp3_worst_case_sdf">

<structure>
  <kernel name="Huffman"/>
  <kernel name="RequantizationLeft"/>
  <kernel name="RequantizationRight"/>
  <kernel name="ReorderLeft"/>
  <kernel name="ReorderRight"/>
  <kernel name="Stereo"/>
  <kernel name="AliasReductionLeft"/>
  <kernel name="AliasReductionRight"/>
  <kernel name="IMDCTLeft"/>
  <kernel name="IMDCTRight"/>
  <kernel name="FrequencyInversionLeft"/>
  <kernel name="FrequencyInversionRight"/>
  <kernel name="SynthesisLeft"/>
  <kernel name="SynthesisRight"/>
  <kernel name="Write"/>
  
  <channel name="H2RQL" source="Huffman" destination="RequantizationLeft" type="data"/>
  <channel name="H2RQR" source="Huffman" destination="RequantizationRight" type="data"/>
  <channel name="RQL2S" source="RequantizationLeft" destination="Stereo" type="data"/>
  <channel name="RQL2ROL" source="RequantizationLeft" destination="ReorderLeft" type="data"/>
  <channel name="RQR2S" source="RequantizationRight" destination="Stereo" type="data"/>
  <channel name="RQR2ROR" source="RequantizationRight" destination="ReorderRight" type="data"/>
  <channel name="ROL2S" source="ReorderLeft" destination="Stereo" type="data"/>
  <channel name="ROR2S" source="ReorderRight" destination="Stereo" type="data"/>
  <channel name="S2ARL" source="Stereo" destination="AliasReductionLeft" type="data"/>
  <channel name="S2IMDCTL" source="Stereo" destination="IMDCTLeft" type="data"/>
  <channel name="S2ARR" source="Stereo" destination="AliasReductionRight" type="data"/>
  <channel name="S2IMDCTR" source="Stereo" destination="IMDCTRight" type="data"/>
  <channel name="ARL2IMDCTL" source="AliasReductionLeft" destination="IMDCTLeft" type="data"/>
  <channel name="ARR2IMDCTR" source="AliasReductionRight" destination="IMDCTRight" type="data"/>
  <channel name="IMDCTL2FIL" source="IMDCTLeft" destination="FrequencyInversionLeft" type="data"/>
  <channel name="IMDCTR2FIR" source="IMDCTRight" destination="FrequencyInversionRight" type="data"/>
  <channel name="FIL2SL" source="FrequencyInversionLeft" destination="SynthesisLeft" type="data"/>
  <channel name="FIR2SR" source="FrequencyInversionRight" destination="SynthesisRight" type="data"/>
  <channel name="SL2W" source="SynthesisLeft" destination="Write" type="data"/>
  <channel name="SR2W" source="SynthesisRight" destination="Write" type="data"/>
  <channel name="W2H" source="Write" destination="Huffman" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="Huffman">
    <scenario name="Default">
      <consume channel="W2H" tokens="1"/>
      <produce channel="H2RQL" tokens="1152"/>
      <produce channel="H2RQR" tokens="1152"/>
      <profile execution_time="236070"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="RequantizationLeft">
    <scenario name="L+S">
      <consume channel="H2RQL" tokens="576"/>
      <produce channel="RQL2S" tokens="576"/>
      <produce channel="RQL2ROL" tokens="576"/>
      <profile execution_time="139325"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="RequantizationRight">
    <scenario name="L+S">
      <consume channel="H2RQR" tokens="576"/>
      <produce channel="RQR2S" tokens="576"/>
      <produce channel="RQR2ROR" tokens="576"/>
      <profile execution_time="139325"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="ReorderLeft">
    <scenario name="S">
      <consume channel="RQL2ROL" tokens="576"/>
      <produce channel="ROL2S" tokens="576"/>
      <profile execution_time="69385"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="ReorderRight">
    <scenario name="S">
      <consume channel="RQR2ROR" tokens="576"/>
      <produce channel="ROR2S" tokens="576"/>
      <profile execution_time="69385"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="Stereo">
    <scenario name="LL+SS">
      <consume channel="RQL2S" tokens="576"/>
      <consume channel="RQR2S" tokens="576"/>
      <produce channel="S2ARL" tokens="576"/>
      <produce channel="S2ARR" tokens="576"/>
      <consume channel="ROL2S" tokens="576"/>
      <consume channel="ROR2S" tokens="576"/>
      <produce channel="S2IMDCTL" tokens="576"/>
      <produce channel="S2IMDCTR" tokens="576"/>
      <profile execution_time="73618"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="AliasReductionLeft">
    <scenario name="BL">
      <consume channel="S2ARL" tokens="18"/>
      <produce channel="ARL2IMDCTL" tokens="18"/>
      <profile execution_time="409"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="AliasReductionRight">
    <scenario name="BL">
      <consume channel="S2ARR" tokens="18"/>
      <produce channel="ARR2IMDCTR" tokens="18"/>
      <profile execution_time="409"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="IMDCTLeft">
    <scenario name="BL+BS">
      <consume channel="ARL2IMDCTL" tokens="6"/>
      <consume channel="S2IMDCTL" tokens="6"/>
      <produce channel="IMDCTL2FIL" tokens="6"/>
      <profile execution_time="7414"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="IMDCTRight">
    <scenario name="BL+BS">
      <consume channel="ARR2IMDCTR" tokens="6"/>
      <consume channel="S2IMDCTR" tokens="6"/>
      <produce channel="IMDCTR2FIR" tokens="6"/>
      <profile execution_time="7414"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="FrequencyInversionLeft">
    <scenario name="BL">
      <consume channel="IMDCTL2FIL" tokens="6"/>
      <produce channel="FIL2SL" tokens="6"/>
      <profile execution_time="4912"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="FrequencyInversionRight">
    <scenario name="BL">
      <consume channel="IMDCTR2FIR" tokens="6"/>
      <produce channel="FIR2SR" tokens="6"/>
      <profile execution_time="4912"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="SynthesisLeft">
    <scenario name="default">
      <consume channel="FIL2SL" tokens="576"/>
      <produce channel="SL2W" tokens="576"/>
      <profile execution_time="1866138"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="SynthesisRight">
    <scenario name="default">
      <consume channel="FIR2SR" tokens="576"/>
      <produce channel="SR2W" tokens="576"/>
      <profile execution_time="1866138"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="Write">
    <scenario name="default">
      <consume channel="SL2W" tokens="1152"/>
      <consume channel="SR2W" tokens="1152"/>
      <produce channel="W2H" tokens="1"/>
      <profile execution_time="42896"/>
    </scenario>
  </kernel_properties>

  <channel_properties channel="W2H" number_of_initial_tokens="9"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/example3.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="example3">

<structure>
  <kernel name="K"/>
  <detector name="D1"/>
  <detector name="D2"/>
  <channel name="D1D2" source="D1" destination="D2" type="control"/>
  <channel name="D2K" source="D2" destination="K" type="control"/>
  <channel name="KD1" source="K" destination="D1" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="K">
    <scenario name="S1">
      <produce channel="KD1" tokens="1"/>
      <profile execution_time="1"/>
    </scenario>
    <scenario name="S2">
      <produce channel="KD1" tokens="1"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>

  <detector_properties detector="D1">
    <subscenario name="S">
      <consume channel="KD1" tokens="1"/>
      <produce channel="D1D2" tokens="1"/>
      <profile execution_time="1"/>
    </subscenario>
    <subscenario name="T">
      <consume channel="KD1" tokens="1"/>
      <produce channel="D1D2" tokens="1"/>
      <profile execution_time="1"/>
    </subscenario>
    <markov_chain initial_state="S">
      <state name="S" subscenario="S">
        <transition destination="S"/>
        <transition destination="T"/>
      </state>
      <state name="T" subscenario="T">
        <transition destination="S"/>
      </state>
    </markov_chain>
  </detector_properties>

  <detector_properties detector="D2">
    <subscenario name="S1">
      <produce channel="D2K" tokens="1"/>
      <profile execution_time="1"/>
    </subscenario>
    <subscenario name="S2">
      <produce channel="D2K" tokens="1"/>
      <profile execution_time="1"/>
    </subscenario>
    <markov_chain scenario="S" initial_state="S2">
      <state name="S1" subscenario="S1">
        <transition destination="S2"/>
      </state>
      <state name="S2" subscenario="S2">
        <transition destination="S1"/>
      </state>
    </markov_chain>
    <markov_chain scenario="T" initial_state="S1">
      <state name="S1" subscenario="S1">
        <transition destination="S2"/>
      </state>
      <state name="S2" subscenario="S2">
        <transition destination="S1"/>
      </state>
    </markov_chain>
  </detector_properties>
  
  <channel_properties channel="KD1" number_of_initial_tokens="3"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/ce_converted_csdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="ce_converted_csdf">

<structure>
  <kernel name="absx"/>
  <kernel name="avg"/>
  <kernel name="log"/>
  <kernel name="lvl"/>
  <kernel name="norm"/>
  <kernel name="cu"/>
  <kernel name="fir"/>
  <kernel name="absy"/>
  <kernel name="cf"/>

  <detector name="load"/>
  
  <channel name="load2absx" source="load" destination="absx" type="data"/>
  <channel name="load2avg" source="load" destination="avg" type="data"/>
  <channel name="load2norm" source="load" destination="norm" type="data"/>
  <channel name="absx2avg" source="absx" destination="avg" type="data"/>
  <channel name="avg2log" source="avg" destination="log" type="data"/>
  <channel name="avg2lvl" source="avg" destination="lvl" type="data"/>
  <channel name="avg2cu" source="avg" destination="cu" type="data"/>
  <channel name="log2lvl" source="log" destination="lvl" type="data"/>
  <channel name="lvl2norm" source="lvl" destination="norm" type="data"/>
  <channel name="lvl2cu" source="lvl" destination="cu" type="data"/>
  <channel name="norm2cu" source="norm" destination="cu" type="data"/>
  <channel name="norm2fir" source="norm" destination="fir" type="data"/>
  <channel name="cu2fir" source="cu" destination="fir" type="data"/>
  <channel name="cu2avg" source="cu" destination="avg" type="data"/>
  <channel name="fir2cf" source="fir" destination="cf" type="data"/>
  <channel name="cf2cu" source="cf" destination="cu" type="data"/>
  <channel name="cf2absy" source="cf" destination="absy" type="data"/>
  <channel name="cf2load" source="cf" destination="load" type="data"/>
  <channel name="absy2cu" source="absy" destination="cu" type="data"/>

  <channel name="control_absx" source="load" destination="absx" type="control"/>
  <channel name="control_avg" source="load" destination="avg" type="control"/>
  <channel name="control_log" source="load" destination="log" type="control"/>
  <channel name="control_lvl" source="load" destination="lvl" type="control"/>
  <channel name="control_cu" source="load" destination="cu" type="control"/>
</structure>

<properties>
  <kernel_properties kernel="absx">
    <scenario name="Phase0">
      <consume channel="load2absx" tokens="1"/>
      <produce channel="absx2avg" tokens="1"/>
      <profile execution_time="144"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="log">
    <scenario name="Phase0">
      <consume channel="avg2log" tokens="1"/>
      <produce channel="log2lvl" tokens="1"/>
      <profile execution_time="144"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="avg">
    <scenario name="Phase0">
      <consume channel="load2avg" tokens="1"/>
      <consume channel="cu2avg" tokens="1"/>
      <consume channel="absx2avg" tokens="1"/>
      <produce channel="avg2lvl" tokens="1"/>
      <produce channel="avg2cu" tokens="1"/>
      <produce channel="avg2log" tokens="1"/>
      <profile execution_time="704"/>
    </scenario>
    <scenario name="Phase1-7">
      <consume channel="load2avg" tokens="1"/>
      <consume channel="cu2avg" tokens="1"/>
      <produce channel="avg2lvl" tokens="1"/>
      <produce channel="avg2cu" tokens="1"/>
      <profile execution_time="416"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="lvl">
    <scenario name="Phase0">
      <consume channel="avg2lvl" tokens="1"/>
      <consume channel="log2lvl" tokens="1"/>
      <produce channel="lvl2cu" tokens="1"/>
      <produce channel="lvl2norm" tokens="1"/>
      <profile execution_time="440"/>
    </scenario>
    <scenario name="Phase1-7">
      <consume channel="avg2lvl" tokens="1"/>
      <produce channel="lvl2cu" tokens="1"/>
      <produce channel="lvl2norm" tokens="1"/>
      <profile execution_time="24"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="cu">
    <scenario name="Phase0">
      <consume channel="avg2cu" tokens="1"/>
      <consume channel="lvl2cu" tokens="1"/>
      <consume channel="norm2cu" tokens="1"/>
      <consume channel="cf2cu" tokens="1"/>
      <consume channel="absy2cu" tokens="1"/>
      <produce channel="cu2avg" tokens="1"/>
      <produce channel="cu2fir" tokens="1"/>
      <profile execution_time="4944"/>
    </scenario>
    <scenario name="Phase1">
      <consume channel="avg2cu" tokens="1"/>
      <consume channel="lvl2cu" tokens="1"/>
      <consume channel="norm2cu" tokens="1"/>
      <consume channel="cf2cu" tokens="1"/>
      <consume channel="absy2cu" tokens="1"/>
      <produce channel="cu2avg" tokens="1"/>
      <produce channel="cu2fir" tokens="1"/>
      <profile execution_time="7648"/>
    </scenario>
    <scenario name="Phase2-7">
      <consume channel="avg2cu" tokens="1"/>
      <consume channel="lvl2cu" tokens="1"/>
      <consume channel="norm2cu" tokens="1"/>
      <consume channel="cf2cu" tokens="1"/>
      <consume channel="absy2cu" tokens="1"/>
      <produce channel="cu2avg" tokens="1"/>
      <produce channel="cu2fir" tokens="1"/>
      <profile execution_time="4944"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="norm">
    <scenario name="default">
      <consume channel="lvl2norm" tokens="1"/>
      <consume channel="load2norm" tokens="1"/>
      <produce channel="norm2cu" tokens="1"/>
      <produce channel="norm2fir" tokens="1"/>
      <profile execution_time="328"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="fir">
    <scenario name="default">
      <consume channel="norm2fir" tokens="1"/>
      <consume channel="cu2fir" tokens="1"/>
      <produce channel="fir2cf" tokens="1"/>
      <profile execution_time="144"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="cf">
    <scenario name="default">
      <consume channel="fir2cf" tokens="1"/>
      <produce channel="cf2cu" tokens="1"/>
      <produce channel="cf2absy" tokens="1"/>
      <produce channel="cf2load" tokens="1"/>
      <profile execution_time="328"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="absy">
    <scenario name="default">
      <consume channel="cf2absy" tokens="1"/>
      <produce channel="absy2cu" tokens="1"/>
      <profile execution_time="144"/>
    </scenario>
  </kernel_properties>

  <detector_properties detector="load">
    <subscenario name="Phase0">
      <consume channel="cf2load" tokens="1"/>
      <produce channel="load2absx" tokens="1"/>
      <produce channel="load2norm" tokens="1"/>
      <produce channel="load2avg" tokens="1"/>
      <produce channel="control_absx" tokens="1"/>
      <produce channel="control_avg" tokens="1"/>
      <produce channel="control_log" tokens="1"/>
      <produce channel="control_lvl" tokens="1"/>
      <produce channel="control_cu" tokens="1"/>
      <profile execution_time="224"/>
    </subscenario>
    <subscenario name="Phase1">
      <consume channel="cf2load" tokens="1"/>
      <produce channel="load2norm" tokens="1"/>
      <produce channel="load2avg" tokens="1"/>
      <produce channel="control_absx" tokens="1"/>
      <produce channel="control_avg" tokens="1" value="Phase1-7"/>
      <produce channel="control_log" tokens="1"/>
      <produce channel="control_lvl" tokens="1" value="Phase1-7"/>
      <produce channel="control_cu" tokens="1"/>
      <profile execution_time="224"/>
    </subscenario>
    <subscenario name="Phase2-7">
      <consume channel="cf2load" tokens="1"/>
      <produce channel="load2norm" tokens="1"/>
      <produce channel="load2avg" tokens="1"/>
      <produce channel="control_absx" tokens="1"/>
      <produce channel="control_avg" tokens="1" value="Phase1-7"/>
      <produce channel="control_log" tokens="1"/>
      <produce channel="control_lvl" tokens="1" value="Phase1-7"/>
      <produce channel="control_cu" tokens="1"/>
      <profile execution_time="224"/>
    </subscenario>
    <markov_chain initial_state="S7">    
      <state name="S0" subscenario="Phase0">
        <transition destination="S1"/>
      </state>
      <state name="S1" subscenario="Phase1">
        <transition destination="S2"/>
      </state>    
      <state name="S2" subscenario="Phase2-7">
        <transition destination="S3"/>
      </state>    
      <state name="S3" subscenario="Phase2-7">
        <transition destination="S4"/>
      </state>    
      <state name="S4" subscenario="Phase2-7">
        <transition destination="S5"/>
      </state>
      <state name="S5" subscenario="Phase2-7">
        <transition destination="S6"/>
      </state>       
      <state name="S6" subscenario="Phase2-7">
        <transition destination="S7"/>
      </state>  
      <state name="S7" subscenario="Phase2-7">
        <transition destination="S0"/>
      </state>       
    </markov_chain>
  </detector_properties>

  <channel_properties channel="cu2avg" number_of_initial_tokens="1"/>
  <channel_properties channel="cf2cu" number_of_initial_tokens="1"/>
  <channel_properties channel="absy2cu" number_of_initial_tokens="1"/>
  <channel_properties channel="cf2load" number_of_initial_tokens="2"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/sdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="sdf">

<structure>
  <kernel name="A"/>
  <kernel name="B"/>
  <kernel name="C"/>
  <channel name="A2B" source="A" destination="B" type="data"/>
  <channel name="B2C" source="B" destination="C" type="data"/>
  <channel name="C2A" source="C" destination="A" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="A">
    <scenario name="default">
      <consume channel="C2A" tokens="1"/>
      <produce channel="A2B" tokens="1"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="B">
    <scenario name="default">
      <consume channel="A2B" tokens="50"/>
      <produce channel="B2C" tokens="2"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="C">
    <scenario name="default">
      <consume channel="B2C" tokens="1"/>
      <produce channel="C2A" tokens="25"/>
      <profile execution_time="1"/>
    </scenario>
  </kernel_properties>
  
  <channel_properties channel="B2C" number_of_initial_tokens="4"/>

</properties>

</sadf>
</sdf3>

=== rhishi/SDF3/sadf/testbench/problem13a.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf3 type="sadf" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="uri:sadf" xsi:schemaLocation="uri:sadf http://www.es.ele.tue.nl/sadf/sdf3-sadf.xsd">
<sadf name="problem13a">

<structure>
  <kernel name="A"/>
  <kernel name="B"/>
  <channel name="A2B" source="A" destination="B" type="data"/>
</structure>

<properties>
  <kernel_properties kernel="A">
    <scenario name="default">
      <produce channel="A2B" tokens="3"/>
      <profile execution_time="1" weight="2"/>
      <profile execution_time="2" weight="8"/>
    </scenario>
  </kernel_properties>

  <kernel_properties kernel="B">
    <scenario name="default">
      <consume channel="A2B" tokens="2"/>
      <profile execution_time="2" weight="3"/>
      <profile execution_time="3" weight="7"/>
    </scenario>
  </kernel_properties>
  
  <channel_properties channel="A2B" buffer_size="6"/>

</properties>

</sadf>
</sdf3>
